Repository Ipuch/bioNC, pull requests merged in 2022-10, with the labels that each got.

#6 bioNC to bionc and maintenance
  .appveyor.yml
  bioNC/segment.py
  bionc/__init__.py
  bionc/model_computations/__init__.py
  bionc/model_computations/biomechanical_model.py
  bionc/model_computations/inertia_parameters.py
  bionc/model_computations/joint.py
  bionc/model_computations/marker.py
  bionc/model_computations/natural_axis.py
  bionc/model_computations/natural_segment.py
  bionc/model_computations/segment.py
  bionc/model_creation/__init__.py
  bionc/model_creation/biomechanical_model_template.py
  bionc/model_creation/c3d_data.py
  bionc/model_creation/inertia_parameters_template.py
  bionc/model_creation/marker_template.py
  bionc/model_creation/natural_axis_template.py
  bionc/model_creation/natural_segment_template.py
  bionc/model_creation/protocols.py
  bionc/model_creation/segment_template.py
  bionc/utils/__init__.py
  bionc/utils/homogenous_transform.py
  bionc/utils/natural_accelerations.py
  bionc/utils/natural_coordinates.py
  bionc/utils/natural_velocities.py
  environment.yml
  examples/forward_dynamics.py
  examples/model_creation.py
  examples/modify_statref.py
  setup.py
  tests/test_homegenous_transform.py
  tests/test_natural_coordinates.py
  tests/test_natural_segment.py
Labels: maintenance

#19 Marker features
  bionc/model_computations/natural_marker.py
  bionc/model_computations/natural_segment.py
  tests/test_marker.py
  tests/test_natural_segment.py
Labels: enhancement

#20 testing biomechanical model class
  bionc/model_computations/biomechanical_model.py
  bionc/model_computations/natural_marker.py
  bionc/model_computations/natural_segment.py
  bionc/utils/natural_coordinates.py
  tests/test_biomech_model.py
  tests/test_natural_coordinates.py
  tests/utils.py
Labels: documentation, enhancement, maintenance

#13 Creation of full coverage of natural_velocities
  tests/test_natural_coordinates.py
  tests/test_natural_velocities.py
Labels: maintenance

#22 Snake case prb
  bionc/model_computations/biomechanical_model.py
  bionc/model_computations/natural_segment.py
  bionc/utils/natural_accelerations.py
  bionc/utils/natural_coordinates.py
  bionc/utils/natural_velocities.py
  examples/forward_dynamics.py
  tests/test_biomech_model.py
  tests/test_natural_coordinates.py
  tests/test_natural_velocities.py
Labels: documentation
